### ISSUE TITLE
Unnecessary resets?

### ISSUE THREAD

**Issue by MarcoMeter** [Unity-Technologies/obstacle-tower-env#100]
I just ran a script that runs my agent on each seed starting at seed 0.
The environment is reset before the beginning of an episode.
In the UnitySDK.log, I observed that there is an additional reset, which is redundant.

Does this mean that the whole tower is getting generated all over again?
In this case, this would waste quite some valuable training time.

```
07/06/2019 10:11:48
 
Log
Setup of CustomOTCEngineLoop done.

Log
Academy resetting

Log
Resetting episode with seed: 37

Log
Academy resetting

Log
Resetting episode with seed: 0

Log
You reached floor: 6

Log
Resetting episode with seed: 0

Log
Academy resetting

Log
Resetting episode with seed: 1

Log
You reached floor: 2

Log
Resetting episode with seed: 1

Log
Academy resetting

Log
Resetting episode with seed: 2

Log
You reached floor: 2

Log
Resetting episode with seed: 2

Log
Academy resetting

Log
Resetting episode with seed: 3

Log
You reached floor: 5

Log
Resetting episode with seed: 3

Log
Academy resetting

Log
Resetting episode with seed: 4
```

**Comment by awjuliani** [comment]
Hi @MarcoMeter 

When the tower resets and the seed and other reset parameters have not changed, then the tower is not regenerated. It is only when one of these things change that the regeneration process takes place.

**Comment by MarcoMeter** [comment]
thanks for the clarification!
