### ISSUE TITLE
v2.2 is still skipping a level

### ISSUE THREAD

**Issue by Sohojoe** [Unity-Technologies/obstacle-tower-env#102]
see https://twitter.com/iAmVidyaGamer/status/1138879798535569408

this is the only instance I've seen

**Comment by awjuliani** [comment]
Hi @Sohojoe 

Thanks for pointing this out. It turns out that this is a separate bug from the previous one. I will look into it tomorrow.

**Comment by awjuliani** [comment]
Hi @Sohojoe 

We've just updated the v2.2 build to change the depth of the entry and exit doors to prevent them from ever overlapping. Let us know if any levels are still skipped!

**Comment by Sohojoe** [comment]
The new version fixes the issue. thanks!
