### ISSUE TITLE
Unable to install otc env in py37

### ISSUE THREAD

**Issue by spMohanty** [Unity-Technologies/obstacle-tower-env#103]
```console
mohanty@node091:/tmp$ which python
/home/mohanty/anaconda3/bin/python

mohanty@node091:/tmp$ python --version
Python 3.7.1

mohanty@node091:/tmp$ pip install mlagents-env==0.6.2
Collecting mlagents-env==0.6.2
  Could not find a version that satisfies the requirement mlagents-env==0.6.2 (from versions: )
No matching distribution found for mlagents-env==0.6.2
mohanty@node091:/tmp$ pip install git+https://github.com/Unity-Technologies/obstacle-tower-env@v2.2
Collecting git+https://github.com/Unity-Technologies/obstacle-tower-env@v2.2
  Cloning https://github.com/Unity-Technologies/obstacle-tower-env (to revision v2.2) to ./pip-req-build-t738tw_j
Collecting mlagents_envs<0.7,>=0.6.2 (from obstacle-tower-env==2.2)
  Could not find a version that satisfies the requirement mlagents_envs<0.7,>=0.6.2 (from obstacle-tower-env==2.2) (from versions: 0.8.0, 0.8.1)
No matching distribution found for mlagents_envs<0.7,>=0.6.2 (from obstacle-tower-env==2.2)
```

**Comment by spMohanty** [comment]
This seems to be causing a lof build failues in the [OTC challenge](https://www.aicrowd.com/challenges/unity-obstacle-tower-challenge) after we upgraded `aicrowd-repo2docker` to use `nvidia/cuda:10.0-cudnn7-runtime-ubuntu18.04` [as the base image](https://discourse.aicrowd.com/t/announcement-aicrowd-repo2docker-base-image-update/1195).

**Comment by Sohojoe** [comment]
@spMohanty  - ml-agents only supports python 3.6 `python_requires=">=3.6,<3.7"` reference https://github.com/Unity-Technologies/ml-agents/blob/master/ml-agents/setup.py

**Comment by spMohanty** [comment]
@Sohojoe : Yeah, I saw that. This issue was mostly for extending support forr `py37`. 
(Though in the short term participants can choose py36 in their runtime specification using `aicrowd-repo2docker`, just a bit worried that it might cause some confusion among participants.

**Comment by awjuliani** [comment]
Hi @spMohanty 

As @Sohojoe says, we are requiring users to have 3.6 as their environment. This has been the case since Round 1, so all participants in Round 2 should know what to do. We make this explicit on the `obstacle-tower-env` page. I am happy to add a notice somewhere else in the documentation if you believe it would be helpful. In a future version of Obstacle Tower we also plan to fully support 3.7.

**Comment by clemens-tolboom** [comment]
Ran into this too. https://github.com/Unity-Technologies/obstacle-tower-env#requirements mentions **3.5 - 3.7** so that is wrong.

```
conda create –name=unityml
conda activate unityml
conda install python=3.6
pip install -e .
```
