### ISSUE TITLE
Is the environment supposed to be deterministic?

### ISSUE THREAD

**Issue by Sohojoe** [Unity-Technologies/obstacle-tower-env#104]
In my experiments (recording inputs, then playing them back on the same level/seed) - sometimes it is deterministic and other times it is not) - I'm not sure if it is a bug in my code or a quirk of the environment

thanks!

**Comment by awjuliani** [comment]
Hi @Sohojoe 

We've done our best to make the environment as deterministic as possible. That being said, Unity physics are inherently non-deterministic, and there will be minor differences between runs.

**Comment by Sohojoe** [comment]
OK thanks!
