### ISSUE TITLE
Problem launching obstacle_tower_env

### ISSUE THREAD

**Issue by djsaunde** [Unity-Technologies/obstacle-tower-env#111]
I installed the latest version of `obstable_tower_env` and downloaded the `obstacletower` binary. Running the notebook and launching the environment, after the "Made with Unity" and "Obstacle Tower Screen", I get the following screen:

![image](https://user-images.githubusercontent.com/1245942/68308324-aad02800-007a-11ea-9e8f-f8501dad2987.png)

I'm running Ubuntu 18.04.3 LTS.

Any idea how to get around this issue?

**Comment by awjuliani** [comment]
Hi @djsaunde 

Sorry you are having issues with the binary. Can you try two things and let me know the results? First, can you launch the binary independently, and ensure that you are able to control the agent using the keyboard? Secondly, when you launch the environment via the jupyter notebook, can you share what information is displayed in the notebook? The application may appear to freeze if it is waiting on a communication command from the python process.

**Comment by djsaunde** [comment]
Hi @awjuliani, thanks for the reply. You're right, the binary just seemed to freeze because it was waiting on communication from python. Looks like everything is working fine!
