### ISSUE TITLE
Is it intended for this theme to show both up and start with the same icon?

### ISSUE THREAD

**Issue by PartiallyTyped** [Unity-Technologies/obstacle-tower-env#113]
I was running OT, initialized from python, with random theme, random seed and here the door to the next floor is the same as the starting door. Is this intended?

<img width="708" alt="Screenshot 2020-01-08 at 11 53 05 AM" src="https://user-images.githubusercontent.com/52372765/71968404-8412a700-320d-11ea-8d2b-527ba65ca603.png">

**Comment by awjuliani** [comment]
Hi @Solliet 

Thank you for pointing this out. It is indeed a small bug in the texture file for the exit door of the "Future" theme which has the arrow direction flipped. I will post a fix.
