### ISSUE TITLE
Visual Observation Size not high resolution (168x168x3)

### ISSUE THREAD

**Issue by vkakerbeck** [Unity-Technologies/obstacle-tower-env#126]
Hello,

I've been working with the Obstacle Tower Environment version 2.2 for a while and have recently downloaded the newest version. However, this new version now always returns observations of size 84x84x3, even if retro mode is set to false. Is there another parameter that I need to set to get the high resolution images again.

To test I run:
from obstacle_tower_env import ObstacleTowerEnv
env = ObstacleTowerEnv(retro=False, realtime_mode=False)
obs = env.reset()
obs[0].shape
>> (84, 84, 3)

I have also tested calling the v4.1 executable with mlagents-learn but get observations of the 84x84 shape even if I set the --width and --height parameter to 168.

Thank you for any help!

**Comment by MarcoMeter** [comment]
Hi @vkakerbeck 

this is an unintended behavior of the provided build. From the source I can tell that the agent's camera sensor is falsely set to 84x84. To solve your issue, a fixed build has to be provided. @awjuliani 

An alternative for you is to make a fixed build yourself from source using [obstacle-tower-source](https://github.com/Unity-Technologies/obstacle-tower-source).

![sensor](https://user-images.githubusercontent.com/6996955/93479644-d8256d80-f8fc-11ea-89d9-5600b149ff12.png)

**Comment by vkakerbeck** [comment]
Hi @MarcoMeter 

thank you for the fast reply and that insight, I thought I was going crazy! I will make a new executable from the source project with the higher resolution then and everything should work fine again :) 
Thank you again and have a great day

**Comment by MarcoMeter** [comment]
No problem.

I just came to think of that you are using v2.2.
If you make a new build, you will have to upgrade to the latest version of obstacle-tower-env as well.
