### ISSUE TITLE
Unusually hard level?

### ISSUE THREAD

**Issue by iandanforth** [Unity-Technologies/obstacle-tower-env#13]
Playing by hand I hit level 15 and encountered a platform that started at natural floor level and then periodically descended. They key for the level was on a raised section of the room to the left of the screenshot. 

<img width="330" alt="screen shot 2019-01-28 at 2 50 38 pm" src="https://user-images.githubusercontent.com/446062/51871827-54280780-230c-11e9-83e2-2db489849b3b.png">

It felt like there might have been a reversed sign somewhere and the platform was supposed to go *up* from ground level. Either that or there was a more complicated solution that I didn't immediately see. :)

**Comment by awjuliani** [comment]
We've addressed this issue in our internal development version of Obstacle Tower, and the version of the binary released for the contest will contain this fix. As such I am closing this issue for now.
