### ISSUE TITLE
Will there be a discussion channel for the challenge?

### ISSUE THREAD

**Issue by seungjaeryanlee** [Unity-Technologies/obstacle-tower-env#18]
Hello again :)

I was wondering if there would be a place for discussion for participants once the challenge starts. In other competitions I have participated (OpenAI Retro Contest, Pommerman, AI for Prosthetics), they had Discord or Gitter set up. They were quite active, and useful ideas would often be communicated.

Thank you!

**Comment by spMohanty** [comment]
@seungjaeryanlee : We will have a gitter channel set up for participants to communicate. There will also be a forum. We will be posting the details once the challenge launches.

**Comment by seungjaeryanlee** [comment]
Wow awesome! Thank you @spMohanty for the blazingly fast reply.
