### ISSUE TITLE
Python requirement

### ISSUE THREAD

**Issue by tduval** [Unity-Technologies/obstacle-tower-env#19]
I think it would be better to write down the minimum and maximum python version requirement, as by default now, every windows 10 comes with Python 3.7.x which is uncompatible with mlagents (python 3.6 max).

**Comment by awjuliani** [comment]
Hi @tduval 

Thanks for pointing this out. We plan to re-evaluate the requirements to simplify them before the official launch of the challenge. There is another github issue about this, that I will consolidate this discussion to. Please feel free to continue this discussion there. https://github.com/Unity-Technologies/obstacle-tower-env/issues/21
