### ISSUE TITLE
Package Dependency from unity-ml is outdated

### ISSUE THREAD

**Issue by wookayin** [Unity-Technologies/obstacle-tower-env#21]
This is mostly from an upstream issue https://github.com/Unity-Technologies/ml-agents/issues/1646, but I believe it's also worth being tracked here as well.

`unity-ml` requires a very specific, outdated version of `tensorflow`, `numpy`, etc. (and python is forced to `>=3.6 <3.7`, which shall be just 3.6+: #19). This would limit users to use recent version of softwares when developing a RL agent on their own, despite there is no reason to get tied to such old versions.

The most standard way: Have `unity-ml` fix https://github.com/Unity-Technologies/ml-agents/issues/1646 (e.g. split the monolithic one into env-related part and learning-related part). But, what else workaround we can think about?

One workaround is simply removing `unity-ml` from its requirements (setup.py), and let users manually install this with `pip install unity-ml --no-deps`, etc. Or we can consider mentioning in the README as well.

**Comment by awjuliani** [comment]
Hi @wookayin 

Thank you for bringing this to our attention. I completely agree that these package requirements are overly restrictive. The current issue is that we are treating both the `mlagents.learn` and `mlagents.envs` packages as one, and using one set of requirements. In fact for Obstacle Tower only `mlagents.envs` is needed, and that package has very few dependencies. I will talk with my team about the best way to approach this in the short term for the competition.

**Comment by awjuliani** [comment]
Hi @wookayin 

This has been addressed in the just-released v1.1 package. Tensorflow and other un-necessary dependencies have been removed. On top of that we expanded the ranges for the required packages. Hopefully this makes for a more straightforward experience.

**Comment by wookayin** [comment]
Great, thanks for your efforts in this! I checked it out and looks good.

**Comment by iamchathu** [comment]
`Collecting mlagents_envs<0.7,>=0.6.2 (from obstacle-tower-env==1.2)
  Could not find a version that satisfies the requirement mlagents_envs<0.7,>=0.6.2 (from obstacle-tower-env==1.2) (from versions: )
No matching distribution found for mlagents_envs<0.7,>=0.6.2 (from obstacle-tower-env==1.2)`

**Comment by awjuliani** [comment]
HI @iamchathu 

What python version are you using?

**Comment by iamchathu** [comment]
System
MacOS 10.14.3
Python 3.7.2 `(Python 3.7.2 (v3.7.2:9a3ffc0492, Dec 24 2018, 02:44:43) [Clang 6.0 (clang-600.0.57)] on darwin)`
pip 19.0.2 `(pip 19.0.2 from /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pip (python 3.7))`

**Comment by iamchathu** [comment]
https://github.com/Unity-Technologies/obstacle-tower-challenge/issues/17

**Comment by awjuliani** [comment]
@iamchathu The `mlagents_envs` package has a requirement for Python 3.7 or lower.

**Comment by iamchathu** [comment]
@awjuliani which version you suggest. Because I had 2.7 default python on mac and i just download the new version from the site.

**Comment by awjuliani** [comment]
@iamchathu Any Python version in the 3.5 or 3.6 range should work.
