### ISSUE TITLE
Bug in stage generation?

### ISSUE THREAD

**Issue by a-maumau** [Unity-Technologies/obstacle-tower-env#22]
Hi, Nice work and I had fun with this game.

I found some bug in stage generation. (It may related to the issue#13 ?)
Sometimes when the character reach to the goal and the next stage has been generated, the character's initial position is very bad/wrong and it will cause an immediate death (sometimes between walls).

**Comment by awjuliani** [comment]
Hi @a-maumau 

Thanks for pointing this issue out. I actually believe it is related to issue #20. I will be looking into the agent/floor reset code and make the changes necessary to ensure that it is both entirely deterministic, and also not impacted by the state of the character when a new floor is loaded.

**Comment by iandanforth** [comment]
@awjuliani I'm seeing something similar in v1.1 (win 10)

Immediately after level transition (when playing by hand) the character be placed outside of the level which causes a reset.

**Comment by awjuliani** [comment]
HI @iandanforth 

By playing by hand do you mean running the binary in player mode (double clicking) or sending specific actions to the python API?

**Comment by iandanforth** [comment]
Player mode. I'll let you know if I encounter it through any programatic interface. I haven't yet.

**Comment by kwea123** [comment]
@iandanforth @awjuliani I start to encounter this after update to v1.1 as well. For v1.0 I didn't experience things like that. I'm on ubuntu 16.04.

**Comment by a-maumau** [comment]
@awjuliani I'm sorry to be late to answer.

My environment is macOS Mojave with the v1.0 binary app. and playing by myself.
Also my mates encountered on Ubuntu 16.04 and 18.04. Both of them are playing on v1.0 binary file by themselves.
So I believe it doesn't depends on OS.

I did not verify (also didn't read any of the source codes) but it might caused by the character's initial velocity at new stage. When I encountered this bug, I always moving in relative high speed which we can get by holding "w" key. So the remain velocity cause the wrong initial positions? (But the phenomenon happens in random, so it is not related?)

I hope this will help a little.

**Comment by kwea123** [comment]
The bug persists in v1.2 (tested with linux). It appears within the first 5 floors.

**Comment by awjuliani** [comment]
Hi all.

This is very strange. I spent a few hours attempting to replicate this issue, without any luck. I will continue attempting to isolate the issue so that I can try to find a fix.

**Comment by kwea123** [comment]
@awjuliani Can you try doing random actions, and save the observation to files? She will jump (or even walk) out of the walls very quickly:
![000_000135](https://user-images.githubusercontent.com/11364490/52893097-30096900-31dc-11e9-9fed-d130ecbbf067.png)

**Comment by awjuliani** [comment]
Hi all,

We have been able to reproduce and isolate the cause of this issue. We plan to have a fix out within 24 hours to address this. Thanks to everyone who shared additional information to help us track it down.

**Comment by awjuliani** [comment]
Hi all,

We have just pushed a new binary version (v1.2) which should fix the issues with the agent falling/exiting the floor. Please check it out here: https://github.com/Unity-Technologies/obstacle-tower-env/tree/v1.2. Be sure to install the latest `obstacle-tower-env` package which is compatible with it.
