### ISSUE TITLE
How to run environment on GCP?

### ISSUE THREAD

**Issue by seungjaeryanlee** [Unity-Technologies/obstacle-tower-env#24]
Hello!

I am unfamiliar with running environments that require rendering on cloud. How can I make it work on a new GCP instance?

Thank you in advance for your assistance.

**Comment by awjuliani** [comment]
Hi @seungjaeryanlee,

We plan to provide a guide on using GCP to train an agent in Obstacle Tower when we officially launch the challenge on February 11th.

**Comment by awjuliani** [comment]
Hi @seungjaeryanlee 

We just released the promised guide. It is available here: https://github.com/Unity-Technologies/obstacle-tower-env/blob/master/examples/gcp_training.md
