### ISSUE TITLE
After jumping once, the charactor will be stuck, and cant jump again.

### ISSUE THREAD

**Issue by breezeyuner** [Unity-Technologies/obstacle-tower-env#25]
platform: Windows7
env: ObstacleTowerEnv

I found a wired bug here:
If the character jump once, after landing, she will be stuck at a gesture, and cant jump again, until she return to the initial standing gesture (but there is no clear method to let her recover to standing gesture, sometimes she will not recover at all even I reset the environment)

The following pictures  are recorded sequentially after I send one jump command, and send blank commands followed repeatedly:
![3 jump1](https://user-images.githubusercontent.com/8111911/52189565-4a565500-2874-11e9-9dcc-5b3654f1be10.png)
![3 jump2](https://user-images.githubusercontent.com/8111911/52189584-6823ba00-2874-11e9-9744-e44ff5b65b7f.png)
![3 jump3](https://user-images.githubusercontent.com/8111911/52189586-6b1eaa80-2874-11e9-820c-2b455de251e4.png)
![3 jump4](https://user-images.githubusercontent.com/8111911/52189588-6c4fd780-2874-11e9-9227-b9c5eae28d2c.png)
![3 jump5](https://user-images.githubusercontent.com/8111911/52189590-6eb23180-2874-11e9-8624-de03cb4c0477.png)
![3 jump6](https://user-images.githubusercontent.com/8111911/52189594-6fe35e80-2874-11e9-9074-7ab1d043b05a.png)
![3 jump7](https://user-images.githubusercontent.com/8111911/52189596-71ad2200-2874-11e9-8245-9090db595ab0.png)
![3 jump8](https://user-images.githubusercontent.com/8111911/52189598-72de4f00-2874-11e9-8c19-739795b4f10a.png)
![3 jump9](https://user-images.githubusercontent.com/8111911/52189600-74a81280-2874-11e9-9ca3-e5db4c33c0ee.png)
![3 jump10](https://user-images.githubusercontent.com/8111911/52189604-7671d600-2874-11e9-80ed-139270e5ffb9.png)
![3 jump11](https://user-images.githubusercontent.com/8111911/52189606-77a30300-2874-11e9-9b98-a0228031c2d7.png)
![3 jump12](https://user-images.githubusercontent.com/8111911/52189614-7f62a780-2874-11e9-9d3d-228d3ba56b62.png)

It is quite clear that the character is stuck at one of the jumping gestures, and cant recover automatically.
What's more, she cant jump again at this status， even I send jump command several times.
![4 jump1](https://user-images.githubusercontent.com/8111911/52189812-f2205280-2875-11e9-8dba-c8c656b1ee12.png)
![4 jump2](https://user-images.githubusercontent.com/8111911/52189813-f3ea1600-2875-11e9-939b-eeb14b6dc3f0.png)
![4 jump3](https://user-images.githubusercontent.com/8111911/52189819-f77d9d00-2875-11e9-872d-21428f757d20.png)

Even I reset the environment, she still stay at the same gesture, and still cant jump.
![4 jump4_reset](https://user-images.githubusercontent.com/8111911/52189677-f009c400-2874-11e9-8f92-c16241cef0b5.png)
 
It is serious if the character cant response to the jump command in that way, please look over it.

**Comment by awjuliani** [comment]
Hi @breezeyuner,

Thanks for pointing this issue out. We are working to fix this bug for the Feb 11 launch of the contest. See this related issue for a discussion of the behavior over reset: https://github.com/Unity-Technologies/obstacle-tower-env/issues/20.

**Comment by awjuliani** [comment]
Hi @breezeyuner 

We just released v1.1 of the Obstacle Tower. This includes improvements to the timing of events in the animation system. I have attempted to reproduce this issue in the new system and have not been able to . As such I am closing the issue for now. If the issue still persists for you, please feel free to re-open.
