### ISSUE TITLE
How can I display the environment in Unity?

### ISSUE THREAD

**Issue by kwea123** [Unity-Technologies/obstacle-tower-env#28]
Can I use python(jupyter notebook) to control the agent, and see the environment in Unity's window? Now it's all dark, I don't know how to turn the graphics on. Thank you.

**Comment by harperj** [comment]
Hi @kwea123, thanks for the message.  In our [basic usage](https://github.com/Unity-Technologies/obstacle-tower-env/blob/master/examples/basic_usage.ipynb) example you can see how to plot the observations received via the Gym environment.

We have discussed adding a method for viewing the environment in the Unity window but don't support it at this time.  I'll discuss with the team how to prioritize this.

**Comment by kwea123** [comment]
Thanks. Because I remember that when I used to use ml-agents (version 0.1, very old..) I can visualize the training and testing in Unity window by setting `env.reset(train_mode=False)`. Is this feature no longer available?

**Comment by harperj** [comment]
@kwea123 this feature is available but isn't exposed for Obstacle Tower right now.  I definitely can see how it would be useful for observing training/test runs.

**Comment by awjuliani** [comment]
Hi @kwea123,

As of v1.2 this feature has been added to Obstacle Tower. You will need the latest binary and python interface which you can get here: https://github.com/Unity-Technologies/obstacle-tower-env/tree/v1.2.
