### ISSUE TITLE
Problem with google.protobuf

### ISSUE THREAD

**Issue by Christopheraburns** [Unity-Technologies/obstacle-tower-env#32]
I *thought* everything was installed properly (Win 10 box, Python3.6 - no Anaconda).
 I am getting this error when trying to run the notebook:

c:\users\chris\appdata\local\programs\python\python36\lib\site-packages\google\protobuf\descriptor.py in <module>
     45   import binascii
     46   import os
---> 47   from google.protobuf.pyext import _message
     48   _USE_C_DESCRIPTORS = getattr(_message, '_USE_C_DESCRIPTORS', False)
     49 

ImportError: DLL load failed: The specified procedure could not be found.

a pip uninstall/install protobuf does not help.   Anyone encountered this error?

**Comment by harperj** [comment]
Hi @Christopheraburns,

I think you've done everything right here :-)

Looks like there's an issue with protobuf 3.6.1 on Windows: https://github.com/protocolbuffers/protobuf/issues/5046

That's the latest version via PyPI: https://pypi.org/project/protobuf/#history

In the Github issue I linked, they mention Python version can be an issue.  Could you share your Python and protobuf versions?  You may need to upgrade Python.

**Comment by Christopheraburns** [comment]
Python = 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)]
Protobuf = 3.6.1

Thanks for the quick response.

**Comment by Christopheraburns** [comment]
FYI - dropping down to Protobuf v3.6.0 via

pip uninstall protobuf
pip install protobuf==3.6.0

Seems to have fixed the problem for me.

**Comment by harperj** [comment]
Glad that works out!  I think updating to Python 3.6.1 would also solve this problem.  I'll close this issue now but please let us know if you run into any more issues.
