### ISSUE TITLE
No Unity Project in Repository

### ISSUE THREAD

**Issue by quentinuys** [Unity-Technologies/obstacle-tower-env#36]
I am unable to find any of the "Game" assets in this project. Could you explain how to open this project in unity.

**Comment by awjuliani** [comment]
Hi @quentinuys,

We are not currently providing the Unity project for this environment. This is because we want to ensure that the challenge which we are about to launch is kept fair. Once the challenge is over in the summer we plan to completely open source the project.

**Comment by kwea123** [comment]
Is there going to be a huge modification on the current release? You mention "For example, we planto add additional visual themes, floor layouts, and interactive elements in future releases" in the paper, is this going to be added to the challenge?

**Comment by quentinuys** [comment]
Hi Arthur.
Thank you for your response.

That is great thank you. You guys rock.

Kind Regards
Quentin Langeveldt

**Comment by awjuliani** [comment]
Hi @kwea123,

During the challenge we will provide a new binary for the second round. This will include an expanded version of the tower with more floor. The higher floors will include additional elements such as visual themes, new kinds of obstacles, and more complex floor layouts. This won't change the layout of the first 25 floors, which are the ones present in the first round, and the current binary.
