### ISSUE TITLE
Character does not move on some rotating obstacles (v1.1)

### ISSUE THREAD

**Issue by Nirenamid** [Unity-Technologies/obstacle-tower-env#37]
Hi!
Maybe there is a bug in the new version (1.1) of environment (downloaded by link from Pull Request #34 ) 
Some obstacles rotate with the character, 
![bug_03 ok](https://user-images.githubusercontent.com/18709286/52521519-4a49c100-2c89-11e9-8d10-4838d6c0f3ed.gif)

but others - without him:
![bug_01](https://user-images.githubusercontent.com/18709286/52521520-533a9280-2c89-11e9-88ad-654ba73f342a.gif)
![bug_02](https://user-images.githubusercontent.com/18709286/52521522-56358300-2c89-11e9-9332-3b060f824cd1.gif)

**Comment by awjuliani** [comment]
Hi @Nirenamid 

Thanks for pointing this out. We don't think it has much impact on agent behavior, but we will be addressing this in the Round 2 release.

**Comment by awjuliani** [comment]
This issue has been addressed in the v2.0 build.
