### ISSUE TITLE
The exact value for each movement and the dimension of the maze

### ISSUE THREAD

**Issue by kwea123** [Unity-Technologies/obstacle-tower-env#38]
For example, moving one step forward is 0.1m; rotating the camera one step is 18 degrees; and the size of the maze (for one block) is 3mx3m...
Is there such a table that we can refer to?

**Comment by kwea123** [comment]
Also, for the actions, can you provide information of what values correspond to what actions? For example the first dimension, does 1 = move forward or 2 = move forward? Same for other actions.

If the above information can be summarized into a table, that would be a huge help. Thanks!

**Comment by breezeyuner** [comment]
I guess all the information you mentioned above is a part of the challenge itself.

**Comment by awjuliani** [comment]
Hi @kwea123,

What each of the actions do is described in cell 3 of the jupyter notebook: https://github.com/Unity-Technologies/obstacle-tower-env/blob/master/examples/basic_usage.ipynb.

The specifics of how those actions impact the environment are something we'd like people to play with and discover themselves. They also vary depending on the presence of obstacles or things like whether the agent is already in motion or not, and are therefore not simple to enumerate.

**Comment by kwea123** [comment]
Thanks all. Closing the issue.
