### ISSUE TITLE
The resolution of the observation

### ISSUE THREAD

**Issue by kwea123** [Unity-Technologies/obstacle-tower-env#39]
Currently it's either 168x168 or 84x84, is there possibility to raise the resolution? Or do you consider that it's already enough for computer vision algorithms to work?

**Comment by awjuliani** [comment]
Hi @kwea123,

There is a trade-off between resolution and speed. Given that almost all DeepRL research has been done in the 84x84 resolution, we believe that giving people 4x this with 168x168 can provide new opportunities for novel network architectures and training methods. 168x168 provides enough detail to solve the task. We have verified this with human players.

**Comment by kwea123** [comment]
Are you talking about ALE games? As what I know, most (or all?) of them are just 2D games, so a small image might just be good. What I want to do in this game is like doing some 3D visual odometry or SLAM-like things. For now it's seems difficult to get it to work, but I will try.

**Comment by awjuliani** [comment]
Not only Atari games, but most of DeepMind's work on the Quake 3 engine is based on 84x84 images. For example, their "Impala" agent uses a 84x84 input: https://arxiv.org/abs/1802.01561. 

Of course in the open source release (coming in the summer) we will make it possible to define your own output resolution, which can be arbitrarily large.
