### ISSUE TITLE
How long does GCP take to run the Dopamine example

### ISSUE THREAD

**Issue by Sohojoe** [Unity-Technologies/obstacle-tower-env#42]
Hi, I've not done much cloud training before so thought I would check it out. Typically how long does it take to train using the Dopamine example?

**Comment by sterlingcrispin** [comment]
The guide says over 24 hours
https://github.com/Unity-Technologies/obstacle-tower-env/blob/master/examples/gcp_training.md

**Comment by awjuliani** [comment]
Hi @Sohojoe 

It takes about two days to reach 10 million training steps.

**Comment by Sohojoe** [comment]
Great, thanks!
