### ISSUE TITLE
Issue Cloning Repo: Permission Denied

### ISSUE THREAD

**Issue by kfezer** [Unity-Technologies/obstacle-tower-env#45]
git clone git@github.com:Unity-Technologies/obstacle-tower-env.git
Cloning into 'obstacle-tower-env'...
Warning: Permanently added the RSA host key for IP address '192.30.255.112' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by kwea123** [comment]
can you try `git clone https://github.com/Unity-Technologies/obstacle-tower-env.git`?

**Comment by kfezer** [comment]
Whurps. That was a silly mistake. Sorry! That worked.
