### ISSUE TITLE
UnityTimeOutException

### ISSUE THREAD

**Issue by aole** [Unity-Technologies/obstacle-tower-env#46]
I am having the exact same issue as issue #44.
Would really appreciate if someone can help me with this.

System: Windows 10
ObstacleTower: v1.1

When I run `env = ObstacleTowerEnv('./ObstacleTower/obstacletower', retro=False)` after installing the requirements I see the following:

The unity splash-screen is displayed, then a tan background appears with the main character briefly in view. She then falls off the screen leaving only the tan background.

Thanks!

**Comment by mehulsuresh** [comment]
Try the old version of the environment (v1) it worked for me. 
Download it at https://storage.googleapis.com/obstacle-tower-build/v1/obstacletower_v1_windows.zip 
for windows

**Comment by Sohojoe** [comment]
I have the same issue on win10 - I was able to get the v1 training. I'm also able to run v1.1 and play manually

**Comment by neutrinum** [comment]
Same here. I updated everything but can only play the v1.1 .exe manually, cannot load it as a UnityEnvironment. The old version (v1) works, but in that version the character cannot jump over walls/blocks as opposed to v1.1

**Comment by awjuliani** [comment]
Hi all,

Can you try this Windows binary and let me know if it works? This resolved the issue for me locally, but I want to ensure that is the case with everyone before pushing it officially: https://storage.googleapis.com/obstacle-tower-build/v1.1/obstacletower_v1.1_windows.zip

**Comment by aole** [comment]
Works for me. It displays a blank window for the game though, is that expected?

Thanks every1 for the reply!

**Comment by louisgv** [comment]
@awjuliani  the new build display a blank window for me as well: 
![image](https://user-images.githubusercontent.com/6723574/52692984-539d8c80-2f1a-11e9-814d-c6d14e0f7e18.png)

**Comment by Sohojoe** [comment]
it is working for me - I get the blank window too (but I think I got this on v1) - also it says its a development build so optimization maybe off. I'll leave it running overnight

**Comment by neutrinum** [comment]
Yes! I also confirm everything seems to run fine so far, thank you. The blank window is also common for me both in v1 and this new version.

**Comment by aole** [comment]
It would be helpful if we can see what the agent is doing @awjuliani .
Can you see the game running in other environments?

**Comment by Sohojoe** [comment]
i am getting "Average training steps per second: 114.58" 

<img width="458" alt="image" src="https://user-images.githubusercontent.com/4400544/52733058-9db45b80-2f76-11e9-859c-867bb91e82f4.png">
with a 1080

**Comment by awjuliani** [comment]
Hi all,

Glad to hear that the new binary resolves the issue for people. The window is black because we disable cameras by default in order to not render frames twice (once to the agent and once to the window). This provides a speed up. We will implement an inference model however so that people can monitor training at realtime with a rendered window.

**Comment by Sohojoe** [comment]
@awjuliani can you push a release version of v1.1.1 - the one in the link is 'development build'

**Comment by aole** [comment]
thanks @awjuliani

**Comment by lezwon** [comment]
@awjuliani can we have the camera issue fixed? I'm getting a black screen right now.

**Comment by MarcoMeter** [comment]
@lezwon The screen is supposed to stay black

@awjuliani Could you provide a fixed Linux build as well?

**Comment by lezwon** [comment]
@MarcoMeter I'd like to see what the agent is doing. Is it possible to enable the cameras?

**Comment by gjossep** [comment]
While using this new development build, calling env.render() does not do anything. I think that its an issue that only happens while running it on windows. Any ideas?

**Comment by awjuliani** [comment]
Hi all,

We have an open PR to enable rendering to the environment window and running at realtime to observe training. That is available here: https://github.com/Unity-Technologies/obstacle-tower-env/pull/50. We plan to add it in a new release of the package in the next day or so.

**Comment by awjuliani** [comment]
Hi all,

We’ve pushed a v1.2 release of the obstacle-tower-env which allows you to run in “real time mode” https://github.com/Unity-Technologies/obstacle-tower-env/tree/v1.2. We also pushed new binaries for Windows and Linux which should address the issues people have been having: https://github.com/Unity-Technologies/obstacle-tower-env/tree/v1.2#download-the-environment
