### ISSUE TITLE
Training on GCP costs

### ISSUE THREAD

**Issue by Abdisalan** [Unity-Technologies/obstacle-tower-env#47]
Excited to start this challenge! I'm concerned about one piece though. How much would you expect I get charged if I were to train on Google Cloud Platform? The quote to use the Deep Learning VM is $294/month and I'd only be using it for this challenge. Ideally it'd be best if I could train on my own machine, but I couldn't find a guide for that.

Sorry to ask here, couldn't find an email for the challenge organizers.

**Comment by awjuliani** [comment]
Hi @Abdisalan 

Most of our guide here (https://github.com/Unity-Technologies/obstacle-tower-env/blob/master/examples/gcp_training.md) can actually be repurposed for training on a local machine.   If you do want to use GCP, a single training session of 10 million steps takes about two days straight of training.
