### ISSUE TITLE
Bug in floor generation with realtime_mode=True

### ISSUE THREAD

**Issue by kwea123** [Unity-Technologies/obstacle-tower-env#54]
When using `realtime_mode=False`, I can set the floor correctly.
![screenshot from 2019-02-16 00-26-23](https://user-images.githubusercontent.com/11364490/52866191-85fcf300-3181-11e9-9893-42da4176deef.png)
But using `realtime_mode=True`, no matter what floor I set, it displays floor 0, and the visual theme is also floor 0:
![screenshot from 2019-02-16 00-28-02](https://user-images.githubusercontent.com/11364490/52866320-be9ccc80-3181-11e9-8025-df53dd0e7ca6.png)
![screenshot from 2019-02-16 00-28-07](https://user-images.githubusercontent.com/11364490/52866325-bfcdf980-3181-11e9-958f-f7d2757428e0.png)

**Comment by awjuliani** [comment]
Hi @kwea123,

Thanks for pointing this out. It is indeed a bug, and we will try to fix it soon.

**Comment by awjuliani** [comment]
Hi @kwea123,

This has been fixed in the new v1.2 binary. Download it here: https://github.com/Unity-Technologies/obstacle-tower-env/tree/v1.2.

**Comment by kwea123** [comment]
I confirm that the bug is fixed.
