### ISSUE TITLE
Environment w/o X server

### ISSUE THREAD

**Issue by miha-skalic** [Unity-Technologies/obstacle-tower-env#55]
Is it possible/how to run the simulator not having X server running?

It being required is a major drawback for usability.

**Comment by MarcoMeter** [comment]
I don't know of any other solution. I'm struggling myself to get this running on CentOS without success yet.

I guess everybody will agree on this being a huge drawback. However, x server is the only thing which one comes across any ml-agents related docs or discussion. Unity needs some display to render to, if visual observations are involved.

**Comment by awjuliani** [comment]
Either a virtual X-server or avfb are required to run Obstacle Tower on a linux machine without a display. https://github.com/Unity-Technologies/obstacle-tower-challenge provides a docker image with xvfb already configured to use for training. We also provide instructions on setting up X-server on GCP here: https://github.com/Unity-Technologies/obstacle-tower-env/blob/master/examples/gcp_training.md

**Comment by miha-skalic** [comment]
Thanks for the reply. 

It appears that Docker will have to do. 

Closing the issue now.
