### ISSUE TITLE
Environment speed on different systems

### ISSUE THREAD

**Issue by miha-skalic** [Unity-Technologies/obstacle-tower-env#58]
Hi,
we are testing the environment on different systems and it turns out that there are major differences in performance. Bellow I report average episode time when performing random actions:
it takes ~16sec on: 
- Intel(R) Xeon(R) Silver 4110 CPU @ 2.10GHz + NVIDIA1080 or 2080TI (driver 410.93; cuda10)

it takes ~4sec on:
- Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz + 780TI (driver 410.73; cuda10)
- Intel(R) Core(TM) i7-3930K CPU @ 3.20GHz + 1080 (driver 410.73; cuda10)

Any ideas why there is such a huge performance difference?

**Comment by miha-skalic** [comment]
I'm leaving the Issue open for now. But it looks more and more like it's an issue with our CPUs and config.

**Comment by awjuliani** [comment]
Hi @miha-skalic 

Can you share a little more information? This may be helpful to other users deciding where to run Obstacle Tower.

**Comment by miha-skalic** [comment]
In this case we had lower level issues, where the CPUs were running at minimal frequency (800MHz), due to some incompatibility (I don't have proper answer how/why, but fixing frequency in bios helped).

It turns out that the performance of obstacle tower is linearly correlated to CPU Frequency.

**Comment by awjuliani** [comment]
Thanks for the information. It is good to know that performance was scaling as expected on your hardware.
