### ISSUE TITLE
Death among stage transition?

### ISSUE THREAD

**Issue by a-maumau** [Unity-Technologies/obstacle-tower-env#60]
Hi, I'm sorry to be like a debugger, but I still encounter a death among stage transition.
Not like #22 , but when the character reach to goal, it immediate started from stage 1.

Is the stage size is limited?
I encountered on stage 29 -> 30. (I think, not sure.)

My environment is macOS 10.14.3, v1.2 and played by myself

**Comment by kwea123** [comment]
There is no stage 29 or 30... The max is 24.
If the character completes level 24, it restarts at level 0.

**Comment by a-maumau** [comment]
I confirmed.
thank you!
