### ISSUE TITLE
Cube's reset floor is in the air.

### ISSUE THREAD

**Issue by a-maumau** [Unity-Technologies/obstacle-tower-env#61]
Position resetting floor/tile of a cube is sometimes in the air.
Is this expected?

<img width="529" alt="screen_shot_obstacle_tower" src="https://user-images.githubusercontent.com/16185203/53237147-4da56980-36d9-11e9-8273-001da6e0cf22.png">

In my case, it was above of a high-level ground (extruded floor).
My environment is macOS 10.14.3, v1.2 and played by myself.

also it might be another issue or is expected, but sometimes if I touch the reset floor, the cube which I did not touch moves to different position which seems to be an initial position.
( I'm not sure on this. It just might be my imagination or something...)

**Comment by a-maumau** [comment]
It seems it is always in the air if the reset floor is placed on the high-level ground.

**Comment by awjuliani** [comment]
Hi @a-maumau 

Thanks for pointing this out. It is indeed a bug, and we will work to fix it in the next release.

**Comment by miha-skalic** [comment]
@awjuliani 

This one might be related.

![ot_bug](https://user-images.githubusercontent.com/7152667/53734407-2e020400-3e84-11e9-9844-e91d659593d7.jpeg)

**Comment by awjuliani** [comment]
@miha-skalic 

I believe so. Both are related to the cube and it's reset area not being placed correctly. This will be addressed in the Round 2 release.

**Comment by unixpickle** [comment]
I opened #80 for the cube-stuck-in-floor bug. Didn't see that it was mentioned in this issue until now.

**Comment by awjuliani** [comment]
Hi all. These issues should be addressed in the v2.0 release. Please re-open the thread if they are still occuring.
