### ISSUE TITLE
How many degrees does the camera turn when a single turn action is taken?

### ISSUE THREAD

**Issue by aole** [Unity-Technologies/obstacle-tower-env#62]
How many degrees does the camera turn when a single turn action is taken? Is this fixed and absolute ie can be used in calculations like x turns will make the character face right?

Since I don't have much processing power to run the whole gamut (360*), I am trying to see if I can reduce the scope by some discrete angle.

**Comment by awjuliani** [comment]
Hi @aole 

Thanks for your question. We don't provide the exact angle that each turn command turns by, but it should be fixed for a given action taken. You should be able to use the python notebook example to determine the number of presses you'd like to use for the macro-actions you seem to be interested in: https://github.com/Unity-Technologies/obstacle-tower-env/blob/master/examples/basic_usage.ipynb

Hopefully this is helpful.

**Comment by aole** [comment]
Thanks @awjuliani
