### ISSUE TITLE
Unexpected keyword argument 'timeout_wait' with latest version

### ISSUE THREAD

**Issue by Holt59** [Unity-Technologies/obstacle-tower-env#63]
With the latest version, I get the following error:

```
TypeError: __init__() got an unexpected keyword argument 'timeout_wait'
```

...when creating an environment on [these lines](https://github.com/Unity-Technologies/obstacle-tower-env/blob/master/obstacle_tower_env.py#L42):

```python
self._env = UnityEnvironment(environment_filename,
                             worker_id,
                             docker_training=docker_training,
                             timeout_wait=timeout_wait)
```

Removing `timeout_wait=timeout_wait` fixes the error.

**Comment by harperj** [comment]
Hi @Holt59 -- if you pulled the most recent version via git, you may have updated this package but not its dependencies (one of which adds `timeout_wait`).  You can test this by running `pip install -e .` in the top level of the cloned repo.

If not, could you share how you installed the new version?

**Comment by Holt59** [comment]
@harperj 

I did perform `pip install -e .`, and I even re-installed `ml-agents` forcing the version to the latest `0.6.*` version available on Windows (do not remember which one it is). Another colleague of mine did the same and faced the same issue.

But I just performed a clean install from scratch on a different machine with the same python version (3.5.4 on Windows), and all went well...

**Comment by Holt59** [comment]
@harperj 

I just tested with the non-working installation and I had messed my virtual environment, which is why this was not working...
