### ISSUE TITLE
multiple environments crash

### ISSUE THREAD

**Issue by DejaVu2** [Unity-Technologies/obstacle-tower-env#64]
![2019-03-01 14-57-47](https://user-images.githubusercontent.com/5326579/53621743-817d1380-3c32-11e9-8576-e7125c49a56e.png)
![2019-03-01 14-58-10](https://user-images.githubusercontent.com/5326579/53621758-8b9f1200-3c32-11e9-904a-d26b10708e47.png)

**Comment by awjuliani** [comment]
Hi @DejaVu2 

Can you provide a little more information about your system, such as OS, whether or not it is headless, etc?

**Comment by DejaVu2** [comment]
Hi @awjuliani Thanks for reply 
![Uploading 2019-03-02 16-08-30屏幕截图.png…]()
![2019-03-02 16-09-58](https://user-images.githubusercontent.com/5326579/53679287-bad28380-3d05-11e9-9c4a-0c5d4d9115e9.png)
It's headless

**Comment by awjuliani** [comment]
Hi @DejaVu2 

What command are you using to run multiple environments?

**Comment by DejaVu2** [comment]
I‘m using OpenAI Baselines.
It seems that Enlighten thread caused a crash.Any recommendation would be very appreciated

**Comment by awjuliani** [comment]
@harperj Do you have some insight?
