### ISSUE TITLE
How to disable the warnings?

### ISSUE THREAD

**Issue by kwea123** [Unity-Technologies/obstacle-tower-env#66]
How to disable the warning when resetting floor, using jupyter notebook?
This is the warning:
```
WARNING:gym_unity:New seed 0 will apply on next reset.
WARNING:gym_unity:New starting floor 0 will apply on next reset.
INFO:mlagents_envs:Academy reset with parameters: floor-number -> 0, tower-seed -> 0
```
It becomes very messy if I try to run the agent with multiple seeds and floors in a for loop.

```
import warnings
warnings.filterwarnings('ignore')
```
What I found on stackoverflow, but this code doesn't work.

**Comment by Holt59** [comment]
You can retrieve the `gym` logger and set its level appropriately:

```python
from obstacle_tower_env import logging, logger
logger.setLevel(logging.ERROR)
```

**Comment by kwea123** [comment]
Thanks, now the `WARNING:` has disappeared. But how can I also disable the `INFO` part?

**Comment by kwea123** [comment]
I got the solution:
```
from obstacle_tower_env import logging
logging.disable(logging.INFO)
logging.disable(logging.WARNING)
```
