### ISSUE TITLE
__MACOSX in obstacletower_v2.0_linux.zip

### ISSUE THREAD

**Issue by htdt** [Unity-Technologies/obstacle-tower-env#90]
The environment zip https://storage.googleapis.com/obstacle-tower-build/v2.0/obstacletower_v2.0_linux.zip contains extra empty folder `__MACOSX`

**Comment by karta1297963** [comment]
It's because the environment is built in macOS of Unity, the macOS will add that folder in zip file, just ignore it.

**Comment by awjuliani** [comment]
Hi @htdt 

Thanks for pointing this out. As @karta1297963 says, it does not impact the use of the binary, but it also should not be there. We will make a note to remove it soon.

**Comment by awjuliani** [comment]
Hi all,

I've just fixed this issue. The builds online no longer contain the added mac hidden files.
