### ISSUE TITLE
Observation Space not updated

### ISSUE THREAD

**Issue by karta1297963** [Unity-Technologies/obstacle-tower-env#93]
The code in obstacle_tower_env.py line138-142

![1](https://user-images.githubusercontent.com/14128307/58013952-5071f800-7b2a-11e9-9742-12b34a9ab33a.PNG)

Seems like the observation space haven't included ```current_floor``` variable, which will make the _flatten_obs(a function in subproc_vec_env.py from OpenAI baseline) not wrapping ```current_floor``` during return of the step function. 

_flatten_obs function:
![2](https://user-images.githubusercontent.com/14128307/58014256-063d4680-7b2b-11e9-9107-f76241228b37.PNG)
in line 198~199 it will only flatten the amount of ```len(observation space)```

**Comment by awjuliani** [comment]
Hi @karta1297963 

Thanks for bringing this up! There is currently an open PR here addressing this: https://github.com/Unity-Technologies/obstacle-tower-env/pull/92. We should hopefully get it in soon, and be able to resolve this issue.

**Comment by awjuliani** [comment]
This has been addressed in v2.1 release. Please re-open if you feel necessary.
