### ISSUE TITLE
Submission problems with v2.0

### ISSUE THREAD

**Issue by Sohojoe** [Unity-Technologies/obstacle-tower-env#96]
I have updated my code for round 2 / version 2 - however I am getting different outcomes on different devices.

When i run the code locally on MacBook native macos (emulating the environments​ that docker has) - it works fine and reproduces results from round 1

When I run the docker code on MacBook it runs the evaluation, but it does scores very badly (average of 1 floor)

When I submit to AI AICrowd - I get an Evaluation Error - see [AI Crowd issue](https://gitlab.aicrowd.com/joe_booth/obstacle-tower-challenge/issues/121)

Could some post my the logs in the [AI Crowd Issue](https://gitlab.aicrowd.com/joe_booth/obstacle-tower-challenge/issues/121)

Thanks!!

**Comment by Sohojoe** [comment]
ping

**Comment by awjuliani** [comment]
Hi @Sohojoe 

Apologies for the delayed response. It was memorial day weekend in the US, and I was not online. Were you able to resolve the issue?

**Comment by Sohojoe** [comment]
yes - the AI Crowd guy posted the logs - it was a v2.1 vs v2 problem. It is scoring as expected so I'm all good now. thanks!

**Comment by spMohanty** [comment]
@Sohojoe : I am assuming that means that that was resolved 👼  !
